"""Signal model for trading signals."""

from datetime import datetime
from enum import Enum

from pydantic import BaseModel, Field


class SignalType(str, Enum):
    """Type of trading signal."""

    BUY = "buy"
    SELL = "sell"
    HOLD = "hold"


class Signal(BaseModel):
    """Trading signal generated by a strategy.

    Represents a decision to buy, sell, or hold based on
    market analysis and model predictions.
    """

    signal_type: SignalType = Field(..., description="Type of signal: buy, sell, hold")
    symbol: str = Field(..., description="Trading pair symbol (e.g., 'BTC/USDT')")
    price: float = Field(..., description="Price at which signal was generated")
    timestamp: datetime = Field(
        default_factory=datetime.now,
        description="When the signal was generated",
    )

    # Optional metadata
    confidence: float | None = Field(
        None, ge=0.0, le=1.0, description="Model confidence score (0-1)"
    )
    model_prediction: float | None = Field(
        None, description="Raw model prediction value"
    )
    reason: str | None = Field(None, description="Human-readable reason for signal")

    # Trailing configuration (passed through to webhook)
    entry_trailing: bool = Field(
        False, description="Whether to use trailing on entry"
    )
    exit_trailing: bool = Field(
        False, description="Whether to use trailing on exit"
    )
    entry_trailing_pct: float = Field(
        0.0, ge=0.0, description="Trailing percentage for entry"
    )
    exit_trailing_pct: float = Field(
        0.0, ge=0.0, description="Trailing percentage for exit"
    )

    @property
    def is_actionable(self) -> bool:
        """Check if signal requires action (not hold)."""
        return self.signal_type != SignalType.HOLD

    model_config = {
        "use_enum_values": True,
    }
